name: TestPlugin
version: 1.0.0
main: com.denisJava.testPlugin.TestPlugin
description: A test plugin
author: DenisJava
website: https://bruh.bruh
api-version: '1.21.4'
permissions:
  storyanvil.command.explode:
    description: "/test explode"
    default: false